### ISSUE TITLE
Dark mode armor icons missing

### ISSUE THREAD

**Issue by WenXin20** [exaskye/NotEnoughCreativity#1]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Not Enough Creativity v1.2`

The Dark Mode armor icons are missing. Strangely, in the previous gameplays I did not see this issue until now, and no other mods were added or updated between launches. I am on a server though.

![2020-12-24_17 35 28](https://user-images.githubusercontent.com/12000593/103111347-bc271b80-4611-11eb-92f3-183bee1100d1.png)

**Comment by exaskye** [comment]
Please send your log.

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/103111472-518fd300-4645-11eb-8dae-26e40d90f1b1.png)

...This also needs looking at.

**Comment by WenXin20** [comment]
I hadn't noticed anything in the logs. And those sort buttons are added by Quark to any chest-like inventory, although the buttons from this mod are overlapping the ones from Quark at the top of the inventory. 

https://gist.github.com/WenXin20/dac15128d6612483c5f3c9bcc0505cce

**Comment by exaskye** [comment]
Very strange that there's no warning printed that my textures are missing. Will make an attempt at a repro soon.

**Comment by WenXin20** [comment]
I also just found out that the long reach will carry over into survival if I change gamemodes. I assume that isn't intended?

**Comment by exaskye** [comment]
> I also just found out that the long reach will carry over into survival if I change gamemodes. I assume that isn't intended?

Fixed in fe106d3e6cc37025d4da68d615ce4ac1739f0aea

**Comment by exaskye** [comment]
It's possible this is fixed in v1.2.2 due to the new way the sprites are injected. Please check.

**Comment by WenXin20** [comment]
Yep, this seems to be fixed. :)
