### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by Nousy-man** [exaskye/NotEnoughCreativity#10]
I was playing on my normal save after just installing this mod. I went to try it out and puff it crashed.
Now it crashes whenever i load the save

[crash-2021-01-28_19.39.47-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/5889102/crash-2021-01-28_19.39.47-server.txt)

**Comment by exaskye** [comment]
Duplicate of #9
