### ISSUE TITLE
All Creative+ Non-Inventory Buttons Delete Items

### ISSUE THREAD

**Issue by ghost** [exaskye/NotEnoughCreativity#12]
The crafting slots, armour slots, and even the Curio button registers as an item deletion slot:
![image](https://user-images.githubusercontent.com/24266948/106444378-c7534e00-64d1-11eb-94a7-bb72a98efeaf.png)

**Comment by ghost** [comment]
This feels similar to what causes #7.

**Comment by exaskye** [comment]
This is because the JEI favorites menu is overlapping the left side of the GUI. Has nothing to do with me; I'm properly reporting my GUI's regions to JEI.

**Comment by exaskye** [comment]
I'll double-check the JEI integ to be sure.

**Comment by ghost** [comment]
Huh, I didn't even notice that lol. At the very least could the UI be 'layered above' such that you can't click through to the favourites menu underneath?

**Comment by exaskye** [comment]
No, I have no control over where JEI decides its regions are other than the API I'm already using, and they're always "above" the inventory.
