### ISSUE TITLE
Crash when clicking to switch to Creative+

### ISSUE THREAD

**Issue by Aulberon** [exaskye/NotEnoughCreativity#13]
The game simply crash when I try to switch modes.
[debug.log](https://github.com/unascribed/NotEnoughCreativity/files/5904810/debug.log)
[crash-2021-02-01_12.23.02-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/5904812/crash-2021-02-01_12.23.02-server.txt)

**Comment by exaskye** [comment]
What the hell?

**Comment by fatpowaranga** [comment]
Can confirm I get the same issue as well. I've tried going as far back as forge-36.0.4 and the same issue still occurs, even if i disable every mod

[latest.log](https://github.com/unascribed/NotEnoughCreativity/files/5911592/latest.log)
[crash-2021-02-02_23.48.44-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/5911598/crash-2021-02-02_23.48.44-server.txt)

**Comment by fatpowaranga** [comment]
As AntauriTV posted on the forge comments, it does appear installing Mantle fixes the issue. Is this intended @unascribed ?

**Comment by exaskye** [comment]
No, and I don't even have Mantle in my test modpack.

**Comment by Aulberon** [comment]
I tried adding Mantle to my mod list and I don't know how, but Creative+ is now working.

**Comment by exaskye** [comment]
I finally had a moment to look into this, and it's because NEC+'s AccessTransformer isn't applying properly. Mantle uses an AT to do the same things NEC+'s would if it were being applied right, so Mantle fixes it entirely by accident.

Currently looking into why the AT is broken.
