### ISSUE TITLE
JEI Bookmarks rendering underneath NEC+ GUI

### ISSUE THREAD

**Issue by Bluberry-Kat** [exaskye/NotEnoughCreativity#14]
presently, the Forge (1.16) build of NEC+ doesn't properly have zones set for JEI item wrapping, meaning bookmarked items will render behind the NEC+ GUI.
![image](https://user-images.githubusercontent.com/20749209/107719473-4f8ddc00-6ca6-11eb-8524-8c65842ee74d.png)

this functions fine with the Fabric build and the 1.12 Forge build.
![image](https://user-images.githubusercontent.com/20749209/107719678-ccb95100-6ca6-11eb-8adf-b30a13f9f5e4.png)
![image](https://user-images.githubusercontent.com/20749209/107719875-36d1f600-6ca7-11eb-977a-f853247ad712.png)

**Comment by exaskye** [comment]
#12 

I really feel like this is a problem with the *incredibly* janky 1.16 JEI, but I'll check this as I mentioned in #12; just haven't gotten around to it.
