### ISSUE TITLE
NEC+ GUI has a single pixel cut-off on the far-right edge

### ISSUE THREAD

**Issue by Bluberry-Kat** [exaskye/NotEnoughCreativity#15]
in the interest of saving space, i will direct you to the images in #14 and only post one here
![image](https://user-images.githubusercontent.com/20749209/107719678-ccb95100-6ca6-11eb-8adf-b30a13f9f5e4.png)

the far-right border of the GUI is missing its black outline. this is still present in the texture so i suspect it's an error in code

**Comment by exaskye** [comment]
I'm supposed to have more attention-to-detail than this.
