### ISSUE TITLE
Mixin Conflict with reach-entity-attributes 

### ISSUE THREAD

**Issue by Bluberry-Kat** [exaskye/NotEnoughCreativity#16]
Using fabric build, NEC+ 1.2.4

When a mod ships [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes), a mixin conflict occurs, preventing NEC+'s Long Reach ability from working properly.

I used [Hard Hat Steve](https://github.com/JamiesWhiteShirt/hard-hat-steve) to test this. 

video for demonstration

https://user-images.githubusercontent.com/20749209/107722855-ea3de900-6cad-11eb-8b81-60399962ac33.mp4

**Comment by Bluberry-Kat** [comment]
oh, forgot. here's my log from the recording session 
[linky link](https://gist.github.com/Birgliss/258978b3e5da051fbea5b1d3b0d4cdd6)

**Comment by exaskye** [comment]
Oh, there's a reach entity attribute lib?

**Comment by Bluberry-Kat** [comment]
there is, as it turns out. i haven't tried to reproduce this on forge, but i think there's a reach attribute in forge by default anyways.

**Comment by exaskye** [comment]
Yes, and NEC+ will make use of it.
