### ISSUE TITLE
Strange behavior when going throw a portal.

### ISSUE THREAD

**Issue by JustSimplyKyle** [exaskye/NotEnoughCreativity#17]
When you have the creative plus inventory open, and go thrkw a portal, your items **seems** to disappear, but you can still click on them and they will still work. And also, when I click on the **switch to creative+** it doesn't switch.

https://user-images.githubusercontent.com/68589851/113552856-580cee00-9629-11eb-8b0e-1fa60d39d72a.mp4

The fix is just changing gamemodes and then it will your files will be visible again.

**Comment by ghost** [comment]
I can confirm that everything goes a bit weird on dimension change - in my case my hotbar items would.. duplicate when I tried to click on them.

Same as you, a gamemode switch fixes the issue.
