### ISSUE TITLE
Mod loading error crash

### ISSUE THREAD

**Issue by CyberFeast2K** [exaskye/NotEnoughCreativity#19]
Was loading the game and crashed. Here is the crash log https://pastebin.com/jppM55rH

**Comment by exaskye** [comment]
Can't load the linked paste.
![image](https://user-images.githubusercontent.com/6185037/114100261-e1662f80-9878-11eb-8251-6ba642d567be.png)

Please use [Gist](https://gist.github.com).

**Comment by CyberFeast2K** [comment]
https://gist.github.com/CyberFeast2K/569dfd54cefb2172d8f293edbf29a14c

**Comment by exaskye** [comment]
> NotEnoughCreativity-Fabric-1.16-1.2.4.jar

> Forge: net.minecraftforge:36.1.3

You have installed the Fabric version of Not Enough Creativity on Forge.

Download the Forge version instead.

**Comment by CyberFeast2K** [comment]
Oh ok, thank you.

**Comment by CyberFeast2K** [comment]
Oh I’m dumb I selected the forge instillation instead of fabric.
