### ISSUE TITLE
No-Clip While Standing = Infinite Fall Into the Void

### ISSUE THREAD

**Issue by TheVisionaryOne** [exaskye/NotEnoughCreativity#2]
If you activate No-Clip mode while standing on the ground, the player will immediately begin falling through the map into the void. There is no way to fly if you have not started flying already, and the only thing spacebar will do is activate the basic Minecraft jump.

Granted, in this weird no-clip falling state, the player can spam jump quickly enough to save themselves if they have a quick reaction, but it could still cause headaches. Even spamming the jump button as quickly as possible doesn't move the player more than 0.5 the speed of normal creative flying.

**Comment by exaskye** [comment]
Oh, fun.
