### ISSUE TITLE
"Allow Damage" Doesn't Allow Fall Damage

### ISSUE THREAD

**Issue by ghost** [exaskye/NotEnoughCreativity#21]
Is this intentional?

**Comment by exaskye** [comment]
Vanilla limitation. Having creative flight enabled at all makes the player immune to fall damage.

I may consider patching that to ignore if you're in Creative+ mode, as if you were to take fall damage with allow damage off it'd just be ignored anyway. If I were to patch the vanilla behavior further, it'd break mods that grant Creative flight to Survival players.

**Comment by ghost** [comment]
Ah, I see. To avoid bloating the tracker with another issue, may I also ask if it's possible to prevent vines, cobwebs, etc. from slowing you down in noclip mode?
