### ISSUE TITLE
Mixin incompatibility crash (Fabric 1.17)

### ISSUE THREAD

**Issue by madimura20** [exaskye/NotEnoughCreativity#27]
Game will crash when starting up game with NEC 1.17 Fabric installed. Seems to be a generic mod conflict, but I cannot tell which mod is causing it from the logs. For some reason, the launcher would not save the full log with a crash info or generate a crash report, so I had to obtain the log "guerrilla-style". I have attached the log with the list of mods installed and the crash info, and let me know if you need any other info or have any other questions.
[latest2.log](https://github.com/unascribed/NotEnoughCreativity/files/7314798/latest2.log)

**Comment by madimura20** [comment]
Updated log with some missing info

**Comment by exaskye** [comment]
Hm. In 1.16, NEC+'s mixin always applies after Reach Entity Attributes' mixin.

I guess I need to do something slightly more advanced...

**Comment by exaskye** [comment]
Got away with just setting the priority, thought I might've needed a mixin config plugin.

**Comment by exaskye** [comment]
Update released and approved on Curse.
