### ISSUE TITLE
onSlotUpdate is missing from ServerPlayerEntity

### ISSUE THREAD

**Issue by madimura20** [exaskye/NotEnoughCreativity#28]
The crash when starting up MC as seen in #27 seems to have been fixed, but now if I switch to Creative+ in my world, the game immediately crashes, with NotEnoughCrashes flagging NEC as the cause of the crash, and it causes the world to be softlocked (crashing upon loading world) until I remove the mod. I'm not sure if it's due to a mod conflict as it does not list any other mod in the crash report, but it appears to have something to do with an "abstract void method" (which I have no idea what that is). I have attached the crash reports and logs below, and let me know if there's any other info you might need.

[crash-2021-10-08_22.48.52-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/7316718/crash-2021-10-08_22.48.52-server.txt)

[crash-2021-10-08_22.50.00-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/7316721/crash-2021-10-08_22.50.00-server.txt)

[2021-10-08-5.log](https://github.com/unascribed/NotEnoughCreativity/files/7316725/2021-10-08-5.log)

**Comment by exaskye** [comment]
Some other mod has messed up ServerPlayerEntity. This error is complete nonsense. A vanilla class is missing an implementation of an important method.

If you can reproduce this with just NEC+ and another mod, then I can look into this, but as it stands this error makes no sense and there are too many mods installed to narrow it down to any specific one.

**Comment by madimura20** [comment]
I started trying on another installation with just NEC+ and basic performance mods, and the mod seemed to work fine. After trying combinations with different mods, I discovered that it is indeed a mod conflict- with the “Skinned Lanterns” mod- that is causing that same error as before. Unfortunately, I’m not sure if much can be done with it due to that mod having no GitHub page (probably means closed source, but I could be wrong). But thanks for the suggestion, it really help to find out which mod is was the culprit.

**Comment by madimura20** [comment]
> 
> I started trying on another installation with just NEC+ and basic performance mods, and the mod seemed to work fine. After trying combinations with different mods, I discovered that it is indeed a mod conflict- with the “Skinned Lanterns” mod- that is causing that same error as before. Unfortunately, I’m not sure if much can be done with it due to that mod having no GitHub page (probably means closed source, but I could be wrong). But thanks for the suggestion, it really help to find out which mod is was the culprit. 

Attached crash reports from tests for reference
[crash-2021-10-10_02.37.00-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/7317036/crash-2021-10-10_02.37.00-server.txt)


[crash-2021-10-10_02.39.33-server.txt](https://github.com/unascribed/NotEnoughCreativity/files/7317038/crash-2021-10-10_02.39.33-server.txt)

**Comment by exaskye** [comment]
Reproduced.

**Comment by exaskye** [comment]
Ultimate cause: Cloth Common Events. It contains a bad mixin.

Skinned Lanterns contains Cloth API via JIJ, which contains Cloth Common Events via JIJ.

Here's a fixed version of Cloth Common Events you can use for now; just put it in your mods dir and it will override the bad one: https://unascribed.com/f/41fe5402_cloth-common-events-v1-2.0.9999.jar

**Comment by madimura20** [comment]
> Here's a fixed version of Cloth Common Events you can use for now; just put it in your mods dir and it will override the bad one: https://unascribed.com/f/41fe5402_cloth-common-events-v1-2.0.9999.jar

Can confirm that with your fixed CCE jar both NEC+ and Skinned Lanterns now work fine without any crashes.
