### ISSUE TITLE
Crash instead of missing mod screen

### ISSUE THREAD

**Issue by WenXin20** [exaskye/NotEnoughCreativity#3]
`Minecraft v1.16.4`
`Forge v35.1.15`
`Not Enough Creativity v1.2.2`

I didn't know that Forgery had to be installed, but instead of showing the missing mod screen, the game crashes. Forgery could also be listed as a mod dependency on Curseforge.
[Crash Report](https://gist.github.com/WenXin20/d1b6f0a227e37294dcd57bb7b1bd5bd7)

**Comment by exaskye** [comment]
Forgery isn't supposed to be a dependency, hold on.

**Comment by exaskye** [comment]
This is what I get for testing my mods in a mini modpack...

**Comment by exaskye** [comment]
Fixed via ForgeryTools update; no commit. Republishing to Curse now...

**Comment by exaskye** [comment]
v1.2.2-fixed published. Sorry about that.

**Comment by WenXin20** [comment]
Ah, no worries!
