### ISSUE TITLE
Spectator-Like Underground Rendering During Noclip

### ISSUE THREAD

**Issue by ghost** [exaskye/NotEnoughCreativity#5]
I am not experienced enough to know if this is possible, however if you noclip into the ground and try to view underground voids / structures, things unload in a way that that simply doesn't happen when you are in spectator mode.

I feel it would be a lot smoother and more comparable to the concept of "spectator mode but creative" if you can actually see underground in the same manner!

**Comment by ghost** [comment]
_P.S. I really love this mod, you have done wonders and everything about it is very clean indeed. The button effects are just amazing lol._

**Comment by exaskye** [comment]
I've noticed this but assumed it was something to do with Sodium. Will look into this more closely.

**Comment by exaskye** [comment]
Fix finally released with v1.2.3 after hitting various bumps and being pulled away for various things today.
