### ISSUE TITLE
Permanent Fullbright after leaving a World with it enabled, persists even after uninstalling.

### ISSUE THREAD

**Issue by megatrook** [exaskye/NotEnoughCreativity#6]
I was testing stuff in my personal modpack but for some reason, permabright is now permanently on, independent of whether i have the mod or whether i'm in creative or not. It seems to have cursed my minecraft installation with fullbright at all times.

**Comment by megatrook** [comment]
Oh and i should note, this is on the Forge 1.16.4 version of the mod

**Comment by exaskye** [comment]
Go to Video Settings and change Brightness from 2000% to something reasonable.

I should adjust this to use a Mixin rather than messing with the game settings.

**Comment by megatrook** [comment]
Yeah, that seemed to fix it! I forgot to update that i figured out how to fix it after the fact. Thank you nonetheless!
