### ISSUE TITLE
Creative+ mode just doesn't work

### ISSUE THREAD

**Issue by Matthysse** [exaskye/NotEnoughCreativity#8]
Hello!
When I click on the button to switch to creative+ mode, nothing happens, and there is that in the log: https://pastebin.com/SiXFgx7W

It's on a singleplayer world (not LAN), and the mod prevented me from opening the world, so I removed it from the modpack and then re placed it and then it does that.

**Comment by exaskye** [comment]
Incompatibility with FastWorkbench; already fixed but I never released it because I wasn't sure if the FastWorkbench author was going to be making more changes.

Releasing now with v1.2.3_01.
